"""Seed a comparison-ready study and remote-work product catalog.

Run with: ``poetry run python -m app.scripts.seed_working_kit_catalog``
"""
from __future__ import annotations

from datetime import datetime, timezone
from decimal import Decimal
from re import sub

from sqlalchemy import select

from app.database import SessionLocal
from app.models import Category, Product, ProductBadge, ProductImage, ProductStatus, Seller, SellerStatus


def slugify(value: str) -> str:
    return sub(r"(^-|-$)", "", sub(r"[^a-z0-9]+", "-", value.lower()))


# Every entry represents one working-kit need. Structured fields deliberately
# distinguish capability, connections and compatibility, so recommendations can
# compare products without treating the description as the source of truth.
WORKING_KIT_PRODUCTS = [
    {"sku": "WORK-001", "name": "Aster 14 Air Laptop", "brand": "Aster", "category": "Laptops", "seller": "Aster Computing", "price": "3299.00", "compare_at_price": None, "description": "Portable 14-inch everyday laptop for coursework, documents, web research and light coding.", "level": "Student / everyday", "specification": "14 in 2.2K IPS; 8-core CPU; 16 GB RAM; 512 GB SSD; Wi-Fi 6E", "connectivity": "2× USB-C, USB-A, HDMI, Wi-Fi 6E, Bluetooth 5.3", "compatibility": "Windows 11; USB-C displays and docks", "dimensions": "31.3 × 22.1 × 1.6 cm; 1.28 kg", "colors": ["Silver", "Midnight Blue"], "warranty": "2-year local warranty", "rating": "4.40", "reviews": 186, "inventory": 27, "image": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=85", "badge": "hot"},
    {"sku": "WORK-002", "name": "Canvas 11 Study Tablet", "brand": "Canvas", "category": "Tablets", "seller": "Canvas Digital", "price": "1899.00", "compare_at_price": "2099.00", "description": "11-inch tablet for handwriting, reading lecture slides, video calls and portable note-taking.", "level": "Student / creative", "specification": "11 in 2K display; 128 GB storage; 8 GB RAM; active stylus support", "connectivity": "USB-C, Wi-Fi 6, Bluetooth 5.2", "compatibility": "Android apps; USB-C keyboards; Canvas Pen 2", "dimensions": "25.0 × 16.5 × 0.7 cm; 480 g", "colors": ["Graphite", "Sage", "Silver"], "warranty": "1-year local warranty", "rating": "4.30", "reviews": 231, "inventory": 43, "image": "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=900&q=85", "badge": "sale"},
    {"sku": "WORK-003", "name": "Vista 27 QHD Monitor", "brand": "Vertex", "category": "Monitors", "seller": "Vertex Displays", "price": "1099.00", "compare_at_price": None, "description": "27-inch QHD monitor with sharp text, height adjustment and accurate colour for work or design.", "level": "Productivity / design", "specification": "27 in IPS; 2560 × 1440; 100 Hz; 99% sRGB; height-adjustable stand", "connectivity": "USB-C 65 W, DisplayPort 1.4, 2× HDMI, USB hub", "compatibility": "Windows, macOS, USB-C laptops", "dimensions": "61.4 × 19.8 × 52.4 cm with stand", "colors": ["Matte Black", "Silver"], "warranty": "3-year panel warranty", "rating": "4.60", "reviews": 149, "inventory": 31, "image": "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=85", "badge": "new"},
    {"sku": "WORK-004", "name": "Nomad 15 Portable Monitor", "brand": "Vertex", "category": "Monitors", "seller": "Vertex Displays", "price": "749.00", "compare_at_price": None, "description": "Slim portable second screen for travel, presentations and dual-screen study sessions.", "level": "Mobile productivity", "specification": "15.6 in IPS; 1920 × 1080; 300 nits; integrated kickstand", "connectivity": "2× USB-C, mini HDMI", "compatibility": "USB-C laptops, tablets, consoles", "dimensions": "35.5 × 22.4 × 0.9 cm; 780 g", "colors": ["Space Gray"], "warranty": "2-year local warranty", "rating": "4.20", "reviews": 97, "inventory": 38, "image": "https://images.unsplash.com/photo-1593640495253-23196b27a87f?auto=format&fit=crop&w=900&q=85", "badge": None},
    {"sku": "WORK-005", "name": "Keyline K87 Mechanical Keyboard", "brand": "Keyline", "category": "Keyboards", "seller": "Keyline Lab", "price": "429.00", "compare_at_price": None, "description": "Compact wireless mechanical keyboard with tactile switches and a comfortable typing angle.", "level": "Developer / writer", "specification": "87-key TKL; hot-swappable tactile switches; PBT keycaps; white backlight", "connectivity": "Bluetooth 5.1, 2.4 GHz receiver, USB-C", "compatibility": "Windows, macOS, iPadOS, Android", "dimensions": "36.0 × 13.5 × 3.5 cm; 860 g", "colors": ["White Gray", "Black"], "warranty": "2-year local warranty", "rating": "4.70", "reviews": 318, "inventory": 56, "image": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=85", "badge": "hot"},
    {"sku": "WORK-006", "name": "Glide S2 Wireless Mouse", "brand": "Glide", "category": "Mice", "seller": "Glide Peripherals", "price": "189.00", "compare_at_price": None, "description": "Quiet ergonomic wireless mouse with multi-device switching for work across laptop and tablet.", "level": "Productivity", "specification": "4,000 DPI optical sensor; 6 buttons; silent clicks; 70-day battery", "connectivity": "Bluetooth, 2.4 GHz receiver", "compatibility": "Windows, macOS, ChromeOS, iPadOS", "dimensions": "11.8 × 7.4 × 4.1 cm; 92 g", "colors": ["Graphite", "White", "Rose"], "warranty": "2-year local warranty", "rating": "4.50", "reviews": 502, "inventory": 84, "image": "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=900&q=85", "badge": None},
    {"sku": "WORK-007", "name": "Orbit XL Desk Mat", "brand": "Orbit", "category": "Desk Accessories", "seller": "Orbit Workspace", "price": "79.00", "compare_at_price": None, "description": "Large water-resistant desk mat that protects the work surface and gives keyboard and mouse a shared base.", "level": "Everyday", "specification": "PU leather; non-slip cork base; spill resistant", "connectivity": "Not applicable", "compatibility": "Keyboard, mouse and laptop desks", "dimensions": "90 × 40 cm", "colors": ["Charcoal", "Tan", "Sage"], "warranty": "6-month manufacturing warranty", "rating": "4.30", "reviews": 274, "inventory": 120, "image": "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=900&q=85", "badge": None},
    {"sku": "WORK-008", "name": "LiftFold Laptop Stand", "brand": "Orbit", "category": "Desk Accessories", "seller": "Orbit Workspace", "price": "119.00", "compare_at_price": None, "description": "Fold-flat aluminum laptop stand with six viewing angles for better screen height and airflow.", "level": "Student / remote work", "specification": "6 height settings; open-frame cooling design; 20 kg load", "connectivity": "Not applicable", "compatibility": "10-17 in laptops and tablets", "dimensions": "24 × 22 × 4 cm folded; 280 g", "colors": ["Silver", "Space Gray"], "warranty": "1-year local warranty", "rating": "4.40", "reviews": 391, "inventory": 96, "image": "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=900&q=85", "badge": "sale"},
    {"sku": "WORK-009", "name": "Arc Single Monitor Arm", "brand": "Orbit", "category": "Desk Accessories", "seller": "Orbit Workspace", "price": "239.00", "compare_at_price": None, "description": "Gas-spring monitor arm that frees desk space and allows smooth height, tilt and rotation adjustment.", "level": "Ergonomic workspace", "specification": "2-9 kg load; 17-32 in screens; 360° rotation; VESA 75/100", "connectivity": "Not applicable", "compatibility": "VESA 75 × 75 or 100 × 100 monitors", "dimensions": "Max reach 52 cm", "colors": ["Matte Black", "White"], "warranty": "3-year local warranty", "rating": "4.50", "reviews": 168, "inventory": 45, "image": "https://images.unsplash.com/photo-1547082299-de196ea013d6?auto=format&fit=crop&w=900&q=85", "badge": None},
    {"sku": "WORK-010", "name": "Studio Oak Work Desk", "brand": "Workwell", "category": "Office Furniture", "seller": "Workwell Studio", "price": "729.00", "compare_at_price": None, "description": "Minimal 120 cm study desk with two drawers and a rear cable opening for focused work.", "level": "Student / home office", "specification": "Two soft-close drawers; 50 kg desktop load", "connectivity": "Cable grommet; no powered ports", "compatibility": "Laptop, monitor arm with clamp up to 5 cm", "dimensions": "W 120 × D 60 × H 75 cm", "colors": ["Oak White", "Walnut Black"], "warranty": "2-year structural warranty", "rating": "4.30", "reviews": 112, "inventory": 19, "image": "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=900&q=85", "badge": None},
    {"sku": "WORK-011", "name": "Posture Pro Ergonomic Chair", "brand": "Workwell", "category": "Office Furniture", "seller": "Workwell Studio", "price": "999.00", "compare_at_price": "1149.00", "description": "Ergonomic chair with adjustable lumbar depth, seat slide and 4D armrests for longer work sessions.", "level": "Professional", "specification": "Synchro tilt; 120 kg load; adjustable headrest; 4D armrests", "connectivity": "Not applicable", "compatibility": "Desks 70-78 cm high", "dimensions": "W 68 × D 67 × H 108-124 cm", "colors": ["Graphite", "Fog Gray"], "warranty": "5-year mechanism warranty", "rating": "4.70", "reviews": 241, "inventory": 22, "image": "https://images.unsplash.com/photo-1505843490538-5133c6c6d0e1?auto=format&fit=crop&w=900&q=85", "badge": "hot"},
    {"sku": "WORK-012", "name": "Balance Memory Foam Footrest", "brand": "Orbit", "category": "Desk Accessories", "seller": "Orbit Workspace", "price": "99.00", "compare_at_price": None, "description": "Rocking memory-foam footrest that supports feet and encourages small movements while seated.", "level": "Ergonomic workspace", "specification": "High-density foam; washable anti-slip cover; reversible rocker", "connectivity": "Not applicable", "compatibility": "Office chairs and desks", "dimensions": "44 × 30 × 12 cm", "colors": ["Black", "Navy"], "warranty": "1-year local warranty", "rating": "4.20", "reviews": 89, "inventory": 71, "image": "https://images.unsplash.com/photo-1497215842964-222b430dc094?auto=format&fit=crop&w=900&q=85", "badge": None},
    {"sku": "WORK-013", "name": "Focus LED Desk Lamp", "brand": "Luma House", "category": "Lighting", "seller": "Luma House", "price": "169.00", "compare_at_price": None, "description": "Flicker-free adjustable desk lamp with touch dimming and a USB-C charging output.", "level": "Study / desk work", "specification": "5 brightness levels; 3 colour temperatures; 800 lm maximum", "connectivity": "USB-C power input; USB-A charging port", "compatibility": "Any desk or bedside table", "dimensions": "Base Ø 17 × H 46 cm", "colors": ["White", "Matte Black"], "warranty": "2-year local warranty", "rating": "4.50", "reviews": 207, "inventory": 64, "image": "https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?auto=format&fit=crop&w=900&q=85", "badge": "new"},
    {"sku": "WORK-014", "name": "ClearCall 1080 Webcam", "brand": "ClearCall", "category": "Video Conferencing", "seller": "ClearCall Tech", "price": "249.00", "compare_at_price": None, "description": "Full-HD webcam with auto-light correction, privacy shutter and dual noise-reduction microphones.", "level": "Remote work", "specification": "1080p at 30 fps; 78° field of view; auto framing", "connectivity": "USB-A with USB-C adapter included", "compatibility": "Windows, macOS, ChromeOS; Teams, Meet, Zoom", "dimensions": "8.1 × 3.3 × 2.8 cm; 105 g", "colors": ["Graphite"], "warranty": "2-year local warranty", "rating": "4.20", "reviews": 156, "inventory": 53, "image": "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?auto=format&fit=crop&w=900&q=85", "badge": None},
    {"sku": "WORK-015", "name": "MeetPro Wireless Headset", "brand": "Sonicraft", "category": "Audio", "seller": "Sonicraft Audio", "price": "359.00", "compare_at_price": "399.00", "description": "On-ear wireless headset with a flip-to-mute boom microphone and all-day battery for calls.", "level": "Remote work", "specification": "40 mm drivers; AI noise-reduction mic; 35-hour battery; multipoint", "connectivity": "Bluetooth 5.3, USB-C, USB-A receiver", "compatibility": "Windows, macOS, iOS, Android; Zoom and Teams", "dimensions": "165 g", "colors": ["Black", "Sand"], "warranty": "2-year local warranty", "rating": "4.40", "reviews": 327, "inventory": 47, "image": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=85", "badge": "sale"},
    {"sku": "WORK-016", "name": "Pods Mini Wireless Earbuds", "brand": "Sonicraft", "category": "Audio", "seller": "Sonicraft Audio", "price": "219.00", "compare_at_price": None, "description": "Compact earbuds with transparency mode and four-mic call clarity for commuting and quick meetings.", "level": "Mobile work", "specification": "ANC; 7 h earbuds + 24 h case; IPX4; touch controls", "connectivity": "Bluetooth 5.3, USB-C charging", "compatibility": "iOS, Android, Windows, macOS", "dimensions": "4.8 g per earbud", "colors": ["White", "Charcoal", "Lilac"], "warranty": "1-year local warranty", "rating": "4.10", "reviews": 468, "inventory": 89, "image": "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=900&q=85", "badge": None},
    {"sku": "WORK-017", "name": "VoiceCast USB Microphone", "brand": "Sonicraft", "category": "Audio", "seller": "Sonicraft Audio", "price": "329.00", "compare_at_price": None, "description": "USB condenser microphone with cardioid pickup, tap-to-mute and real-time headphone monitoring.", "level": "Creator / professional calls", "specification": "24-bit / 96 kHz; cardioid capsule; gain control; shock mount included", "connectivity": "USB-C; 3.5 mm headphone out", "compatibility": "Windows, macOS, iPadOS, OBS, Discord", "dimensions": "H 18.5 cm; 410 g", "colors": ["Black", "White"], "warranty": "2-year local warranty", "rating": "4.60", "reviews": 193, "inventory": 36, "image": "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=900&q=85", "badge": "hot"},
    {"sku": "WORK-018", "name": "Port 8-in-1 USB-C Hub", "brand": "Portworks", "category": "Connectivity", "seller": "Portworks", "price": "179.00", "compare_at_price": None, "description": "Compact USB-C hub adding display, USB and card-reader ports to modern laptops and tablets.", "level": "Student / travel", "specification": "4K HDMI 60 Hz; 100 W PD pass-through; 2× USB-A; SD/microSD", "connectivity": "USB-C host; HDMI; USB-A; SD; USB-C PD", "compatibility": "USB-C devices supporting DisplayPort Alt Mode", "dimensions": "11.5 × 4.3 × 1.4 cm; 82 g", "colors": ["Space Gray", "Silver"], "warranty": "2-year local warranty", "rating": "4.30", "reviews": 377, "inventory": 104, "image": "https://images.unsplash.com/photo-1625948515291-69613efd103f?auto=format&fit=crop&w=900&q=85", "badge": None},
    {"sku": "WORK-019", "name": "DockOne Thunderbolt Station", "brand": "Portworks", "category": "Connectivity", "seller": "Portworks", "price": "899.00", "compare_at_price": None, "description": "Single-cable desktop dock for dual displays, wired networking and fast external storage.", "level": "Professional / developer", "specification": "Thunderbolt 4; dual 4K 60 Hz; 2.5 GbE; 96 W laptop charging", "connectivity": "Thunderbolt 4, 2× HDMI, DisplayPort, USB-C, USB-A, Ethernet", "compatibility": "Thunderbolt 4/USB4 laptops; Windows and macOS", "dimensions": "19.0 × 8.0 × 3.0 cm", "colors": ["Space Gray"], "warranty": "3-year local warranty", "rating": "4.50", "reviews": 83, "inventory": 18, "image": "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=85", "badge": "new"},
    {"sku": "WORK-020", "name": "Vault 1TB Portable SSD", "brand": "Vault", "category": "Storage", "seller": "Vault Storage", "price": "469.00", "compare_at_price": "529.00", "description": "Pocketable rugged external SSD for project files, backups and fast media transfers.", "level": "Student / creator", "specification": "1 TB NVMe SSD; up to 1,050 MB/s; IP65 dust and water resistance", "connectivity": "USB-C 3.2 Gen 2; USB-A cable included", "compatibility": "Windows, macOS, iPadOS, Android", "dimensions": "10.5 × 5.8 × 1.0 cm; 70 g", "colors": ["Black", "Blue"], "warranty": "5-year limited warranty", "rating": "4.70", "reviews": 278, "inventory": 61, "image": "https://images.unsplash.com/photo-1531492746076-161ca9bcad58?auto=format&fit=crop&w=900&q=85", "badge": "sale"},
    {"sku": "WORK-021", "name": "ChargeGo 20K Power Bank", "brand": "Voltway", "category": "Power", "seller": "Voltway", "price": "249.00", "compare_at_price": None, "description": "20,000 mAh power bank with USB-C fast charging for a laptop top-up and multiple phone charges.", "level": "Travel / remote work", "specification": "20,000 mAh; 65 W USB-C PD; airline-safe; digital battery display", "connectivity": "2× USB-C, USB-A", "compatibility": "USB-C laptops, tablets, phones and accessories", "dimensions": "15.2 × 7.2 × 2.6 cm; 345 g", "colors": ["Black", "Sand"], "warranty": "2-year local warranty", "rating": "4.40", "reviews": 352, "inventory": 74, "image": "https://images.unsplash.com/photo-1609592424824-3b0e6b4b2b98?auto=format&fit=crop&w=900&q=85", "badge": None},
    {"sku": "WORK-022", "name": "GaN 100 Multi-Port Charger", "brand": "Voltway", "category": "Power", "seller": "Voltway", "price": "279.00", "compare_at_price": None, "description": "Compact GaN wall charger that powers a laptop, tablet and phone from one travel-friendly adapter.", "level": "Travel / multi-device", "specification": "100 W total; 3× USB-C PD; USB-A QC; foldable plug", "connectivity": "3× USB-C, USB-A", "compatibility": "USB-C PD laptops, tablets, phones", "dimensions": "7.0 × 6.5 × 3.2 cm; 190 g", "colors": ["White", "Black"], "warranty": "2-year local warranty", "rating": "4.60", "reviews": 221, "inventory": 79, "image": "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=900&q=85", "badge": "hot"},
    {"sku": "WORK-023", "name": "SafeLine Surge Extension", "brand": "Voltway", "category": "Power", "seller": "Voltway", "price": "129.00", "compare_at_price": None, "description": "Six-outlet surge-protected extension with individual safety shutters and two USB charging ports.", "level": "Home office safety", "specification": "2,400 W maximum; 900 J surge protection; 2 m cable; overload switch", "connectivity": "6× UK outlets, USB-A, USB-C", "compatibility": "Malaysian 240 V home and office devices", "dimensions": "31 × 11 × 4 cm", "colors": ["White", "Black"], "warranty": "2-year local warranty", "rating": "4.30", "reviews": 411, "inventory": 113, "image": "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=900&q=85", "badge": None},
    {"sku": "WORK-024", "name": "Route Cable Management Kit", "brand": "Orbit", "category": "Desk Accessories", "seller": "Orbit Workspace", "price": "69.00", "compare_at_price": None, "description": "Complete cable-organising kit with sleeve, under-desk tray, clips and reusable hook-and-loop ties.", "level": "Desk organisation", "specification": "1.5 m cable sleeve; 40 clips; steel tray; 20 reusable ties", "connectivity": "Not applicable", "compatibility": "Desks up to 5 cm thick", "dimensions": "Tray W 40 × D 12 × H 10 cm", "colors": ["Black", "White"], "warranty": "1-year local warranty", "rating": "4.20", "reviews": 263, "inventory": 127, "image": "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=900&q=85", "badge": "sale"},
    {"sku": "WORK-025", "name": "Grid Desk Drawer Organizer", "brand": "Orbit", "category": "Desk Accessories", "seller": "Orbit Workspace", "price": "59.00", "compare_at_price": None, "description": "Expandable drawer organiser with modular trays for stationery, adapters, cables and small devices.", "level": "Desk organisation", "specification": "6 modular trays; expandable width; wipe-clean finish", "connectivity": "Not applicable", "compatibility": "Drawers 30-48 cm wide", "dimensions": "30-48 × 38 × 5 cm", "colors": ["White", "Charcoal", "Sage"], "warranty": "1-year local warranty", "rating": "4.10", "reviews": 198, "inventory": 108, "image": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=85", "badge": None},
    {"sku": "WORK-026", "name": "WeekView Undated Planner", "brand": "Paperline", "category": "Stationery", "seller": "Paperline Studio", "price": "39.00", "compare_at_price": None, "description": "Undated 12-month weekly planner with monthly goals, task lists and project pages.", "level": "Student / planner", "specification": "A5; 160 gsm paper; lay-flat binding; 192 pages", "connectivity": "Not applicable", "compatibility": "Pens, highlighters and stickers", "dimensions": "14.8 × 21 cm", "colors": ["Sand", "Sage", "Navy"], "warranty": "Not applicable", "rating": "4.50", "reviews": 327, "inventory": 135, "image": "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=900&q=85", "badge": "new"},
    {"sku": "WORK-027", "name": "PlanBoard Magnetic Memo Board", "brand": "Paperline", "category": "Stationery", "seller": "Paperline Studio", "price": "149.00", "compare_at_price": None, "description": "Wall-mount magnetic whiteboard for schedules, deadlines and visual project planning.", "level": "Study / team planning", "specification": "Magnetic steel surface; dry-erase; marker tray; mounting kit", "connectivity": "Not applicable", "compatibility": "Dry-erase markers, magnets and notes", "dimensions": "W 90 × H 60 cm", "colors": ["White", "Black Frame", "Oak Frame"], "warranty": "1-year local warranty", "rating": "4.30", "reviews": 76, "inventory": 46, "image": "https://images.unsplash.com/photo-1516321165247-4aa89a48be28?auto=format&fit=crop&w=900&q=85", "badge": None},
    {"sku": "WORK-028", "name": "Commute 20L Laptop Backpack", "brand": "Northline", "category": "Bags", "seller": "Northline Outdoor", "price": "219.00", "compare_at_price": None, "description": "Weather-resistant 20 L work backpack with a suspended 16-inch laptop compartment and quick-access pockets.", "level": "Student / commuter", "specification": "20 L; padded 16 in laptop sleeve; bottle pocket; luggage pass-through", "connectivity": "USB-C cable pass-through", "compatibility": "Laptops up to 16 in", "dimensions": "W 30 × D 16 × H 45 cm", "colors": ["Black", "Navy", "Moss"], "warranty": "2-year local warranty", "rating": "4.60", "reviews": 284, "inventory": 57, "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=85", "badge": None},
    {"sku": "WORK-029", "name": "ThermoSip Insulated Tumbler", "brand": "ThermoSip", "category": "Lifestyle Accessories", "seller": "ThermoSip", "price": "89.00", "compare_at_price": None, "description": "Leak-resistant 600 ml tumbler that keeps drinks cold through a long workday or commute.", "level": "Everyday", "specification": "600 ml; double-wall vacuum insulation; straw and sip lids included", "connectivity": "Not applicable", "compatibility": "Most car cup holders", "dimensions": "H 22 × Ø 8 cm", "colors": ["White", "Sage", "Navy", "Coral"], "warranty": "1-year local warranty", "rating": "4.40", "reviews": 692, "inventory": 165, "image": "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=85", "badge": "hot"},
    {"sku": "WORK-030", "name": "Breeze Mini Air Circulator", "brand": "Luma House", "category": "Desk Accessories", "seller": "Luma House", "price": "139.00", "compare_at_price": "159.00", "description": "Quiet desktop air circulator with adjustable tilt and four speeds for warm study corners.", "level": "Desk comfort", "specification": "4 speeds; 70° tilt; 8-hour timer; 28 dB on low", "connectivity": "USB-C power; 2 m cable", "compatibility": "Desk, bedside table or shelf", "dimensions": "W 18 × D 14 × H 22 cm", "colors": ["White", "Charcoal", "Sage"], "warranty": "2-year local warranty", "rating": "4.20", "reviews": 144, "inventory": 68, "image": "https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=900&q=85", "badge": "sale"},
]


def run() -> int:
    with SessionLocal() as db:
        sellers: dict[str, Seller] = {}
        categories: dict[str, Category] = {}
        for position, item in enumerate(WORKING_KIT_PRODUCTS, start=1):
            seller_name = item["seller"]
            seller_slug = slugify(seller_name)
            seller = sellers.get(seller_slug) or db.scalar(select(Seller).where(Seller.slug == seller_slug))
            if seller is None:
                seller = Seller(name=seller_name, slug=seller_slug, description=f"Work and study merchant profile for {seller_name}.", status=SellerStatus.ACTIVE)
                db.add(seller)
                db.flush()
            else:
                seller.status = SellerStatus.ACTIVE
            sellers[seller_slug] = seller

            category_name = item["category"]
            category_slug = slugify(category_name)
            category = categories.get(category_slug) or db.scalar(select(Category).where(Category.slug == category_slug))
            if category is None:
                category = Category(name=category_name, slug=category_slug, description=f"Study and work products: {category_name}.", sort_order=300 + position, is_active=True)
                db.add(category)
                db.flush()
            categories[category_slug] = category

            product = db.scalar(select(Product).where(Product.sku == item["sku"]))
            values = {
                "seller": seller, "category": category, "slug": slugify(item["name"]), "name": item["name"], "brand": item["brand"],
                "description": item["description"], "price": Decimal(item["price"]),
                "compare_at_price": Decimal(item["compare_at_price"]) if item["compare_at_price"] else None, "currency": "MYR",
                "status": ProductStatus.ACTIVE, "badge": ProductBadge(item["badge"]) if item["badge"] else None,
                "inventory_quantity": item["inventory"], "reserved_quantity": 0, "emoji": "💻",
                "specs": [
                    {"label": "Level", "value": item["level"]}, {"label": "Key specifications", "value": item["specification"]},
                    {"label": "Connectivity", "value": item["connectivity"]}, {"label": "Compatibility", "value": item["compatibility"]},
                    {"label": "Size / weight", "value": item["dimensions"]}, {"label": "Colour options", "value": ", ".join(item["colors"])},
                    {"label": "Warranty", "value": item["warranty"]}, {"label": "Seller", "value": seller_name},
                ],
                "attributes": {
                    "department": "study-working-kit", "level": item["level"], "specification": item["specification"],
                    "connectivity": item["connectivity"], "compatibility": item["compatibility"], "dimensions": item["dimensions"],
                    "colors": item["colors"], "warranty": item["warranty"],
                },
                "rating_average": Decimal(item["rating"]), "review_count": item["reviews"], "published_at": datetime.now(timezone.utc),
            }
            if product is None:
                product = Product(sku=item["sku"], **values)
                db.add(product)
            else:
                for field, value in values.items():
                    setattr(product, field, value)
            db.flush()
            primary_image = min(product.images, key=lambda image: image.sort_order) if product.images else None
            if primary_image is None:
                product.images.append(ProductImage(url=item["image"], alt_text=item["name"], sort_order=0))
            else:
                primary_image.url = item["image"]
                primary_image.alt_text = item["name"]
                primary_image.sort_order = 0
        db.commit()
    print(f"Working-kit catalog seed complete: {len(WORKING_KIT_PRODUCTS)} products upserted.")
    return 0


if __name__ == "__main__":
    raise SystemExit(run())
