import { notFound } from "next/navigation";
import type { Metadata } from "next";
import styles from "./legal-document.module.css";

const documents = {
  terms: { title: "Terms of Service", summary: "The rules for using Shopy, placing orders, and managing your account.", sections: [["Using Shopy", "You may use Shopy to browse products, receive AI-assisted recommendations, and make purchases for lawful personal or business purposes. Keep your account details accurate and protect your sign-in credentials."], ["Orders and payments", "An order is confirmed when Shopy displays a confirmation screen or sends a confirmation email. Prices, stock availability, delivery estimates, and promotions may change before an order is confirmed. We may cancel an order if payment cannot be authorised, stock is unavailable, or there is a clear pricing error."], ["Returns and refunds", "Eligible items may be returned within 14 days of delivery when unused and in their original condition. Refund timing depends on the original payment method and issuing provider. Some personal-care, made-to-order, and final-sale items may be excluded; the item page will say when that applies."], ["Your content and feedback", "If you submit reviews, feedback, or shopping preferences, you allow Shopy to use them to operate and improve the service. Do not upload content that is unlawful, misleading, or infringes someone else's rights."]] },
  privacy: { title: "Privacy Policy", summary: "How Shopy uses personal information to provide a useful, secure shopping experience.", sections: [["Information we collect", "We collect details you give us, such as your name, email address, delivery address, and support messages. We also collect order activity, device information, and product interactions needed to run the service."], ["How we use information", "We use information to process orders, provide customer support, prevent fraud, improve the platform, and personalise recommendations. Recommendation signals help tailor shopping suggestions; they are not used to make decisions about credit, employment, or insurance."], ["When information is shared", "We share only what is needed with delivery partners, payment processors, service providers, and sellers that fulfil your order. We may also disclose information where required by law or to protect Shopy and our customers from fraud or abuse."], ["Your choices", "You can update account information in Profile, control marketing emails through their unsubscribe link, and ask us to access, correct, or delete eligible personal information. Contact privacy@shopy.example for privacy requests."]] },
  cookies: { title: "Cookie Policy", summary: "How Shopy uses cookies and similar technologies to keep the platform working well.", sections: [["What cookies do", "Cookies are small files stored by your browser. They help us remember your session, keep your cart available, understand platform performance, and show relevant content."], ["Essential cookies", "These cookies support core functions such as sign-in, checkout, fraud prevention, and load balancing. You cannot opt out of essential cookies while using Shopy because the service would not work reliably without them."], ["Analytics and preference cookies", "With your consent where required, Shopy uses analytics and preference cookies to understand feature use and remember choices such as language, region, and recently viewed items. We use aggregate reporting to improve the experience."], ["Managing cookies", "Most browsers let you review, block, or delete cookies in their settings. Blocking some cookies can affect sign-in, saved carts, recommendations, and checkout. You can refresh cookie choices from the privacy controls in your account when available."]] },
  security: { title: "Security at Shopy", summary: "The practical safeguards Shopy uses to help protect accounts, payments, and orders.", sections: [["Account protection", "We use encrypted connections and protective monitoring to help keep accounts secure. Use a unique password, do not share sign-in codes, and sign out of shared devices. We will never ask for your password through an unsolicited message."], ["Payments", "Payment details are handled by approved payment providers using industry-standard security controls. Shopy does not display your full card number in your account or order history."], ["Security monitoring", "We monitor for suspicious sign-ins, payment activity, and order patterns. To protect customers, we may ask for additional verification or temporarily pause an order while we review unusual activity."], ["Report a concern", "If you think your account has been accessed without permission, change your password immediately and contact security@shopy.example. For security research reports, email security@shopy.example with enough detail for our team to reproduce the issue."]] },
} as const;

type DocumentKey = keyof typeof documents;
export function generateStaticParams() { return Object.keys(documents).map((document) => ({ document })); }
export async function generateMetadata({ params }: { params: Promise<{ document: string }> }): Promise<Metadata> { const { document } = await params; const item = documents[document as DocumentKey]; return item ? { title: `${item.title} | Shopy`, description: item.summary } : {}; }
export default async function LegalDocumentPage({ params }: { params: Promise<{ document: string }> }) { const { document } = await params; const item = documents[document as DocumentKey]; if (!item) notFound(); return <article className={styles.page}><header className={styles.hero}><p>Shopy legal centre</p><h1>{item.title}</h1><span>{item.summary}</span><small>Effective: 9 September 2026 · This is a demonstration policy for the Shopy platform.</small></header><div className={styles.content}>{item.sections.map(([heading, body], index) => <section key={heading}><span>{String(index + 1).padStart(2, "0")}</span><div><h2>{heading}</h2><p>{body}</p></div></section>)}</div><aside className={styles.contact}>Questions about this policy? Contact <a href="mailto:support@shopy.example">support@shopy.example</a>.</aside></article>; }
